### ISSUE TITLE
atmos plot set 15 GUI

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcmetrics#100]
The GUI doesn't draw plots for the same problem which is successful with the command-line, in atmosphere plot set 15.  There are error messages about not being able to find or compute variables.

**Comment by mcenerney1** [comment]
I was able to run gui and command line successfully for
diags.py --model path=$HOME/uvcmetrics_test_data/cam35_data/,climos=yes --obs path=$HOME/uvcmetrics_test_data/obs_data/,filter='f_startswith("NCEP")',climos=yes --outputdir $HOME/Documents/Climatology/ClimateData/diagout/ --package AMWG --sets 15 --seasons ANN --plots yes --vars T
