### ISSUE TITLE
plots shouldn't be represented with tuples

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcmetrics#102]
When we had an urgent need to support vector plots (atmosphere plot set 7) I used tuples to represent the vectors.  Something similar is not in atmos set 12.  Unfortunately, this is an awkward data structure because it doesn't have the machinery we need to handle plots.  So we need lots of special-case code to handle them.  Such code isn't, and shouldn't be, in the GUI.

We need to replace these tuples with a better data structure.  Once that is done, it will be practical to support atmos plots 7 & 12 in the GUI.

**Comment by painter1** [comment]
The vector plots I had in mind were plot set 6, not 7.

**Comment by mcenerney1** [comment]
With the pull request in UV-CDAT/VisTrails, branch plot_spec_6, this capability is available for Scatter plots and Vector plots.
