### ISSUE TITLE
Taylor diagrams (plot set 14)

### ISSUE THREAD

**Issue by mcenerney1** [UV-CDAT/uvcmetrics#104]
Running from the gui, Taylor diagrams fail, since the presentation has no datawc_x1, etc.

Traceback (most recent call last):
  File "/usr/local/uvcdat/03_04_2015/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 626, in buttonClicked
    self.applyClicked()
  File "/usr/local/uvcdat/03_04_2015/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 743, in applyClicked
    self.displayCell(res30, row, col)
  File "/usr/local/uvcdat/03_04_2015/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 764, in displayCell
    print "x min,max:",presentation.datawc_x1, presentation.datawc_x2
AttributeError: 'Gtd' object has no attribute 'datawc_x1'

**Comment by painter1** [comment]
The error is in diagnostic code.  But the attributes datawc_x1, etc. should always be set.  I'll make sure that they default to None and push the bugfix later today.

**Comment by doutriaux1** [comment]
@painter1 taylordiagram does NOT have such attributes.

**Comment by doutriaux1** [comment]
```
In [1]: td=x.createtaylordiagram()

In [2]: td.list()
 ----------Taylordiagram (Gtd) member (attribute) listings ----------
graphic method = Gtd
name = __taylordiagram_567639755593443
detail = 75
max = None
quadrans = 1
skillValues = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95]
skillColor = 252
skillDrawLabels = y
skillCoefficient = [1.0, 1.0, 1.0]
referencevalue = 1.0
arrowlength = 0.05
arrowangle = 20.0
arrowbase = 0.75
xticlabels1 = *
xmtics1 = *
yticlabels1 = *
ymtics1 = *
cticlabels1 = *
cmtics1 = *
Marker
    status =  []
    line =  []
    id =  []
    id_size =  []
    id_color =  []
    id_font =  []
    symbol =  []
    color =  []
    size =  []
    xoffset =  []
    yoffset =  []
    line_color =  []
    line_size =  []
    line_type =  []
```

**Comment by painter1** [comment]
Those attributes would make no sense in a Taylor diagram.  The place where they should default to None is not in a VCS object.  It's in a uvc_simple_plotspec object of the diagnostics package.  They make no sense there in this case either, but it will simplify overall coding if they always exist.  "None" was invented for this sort of situation.

**Comment by doutriaux1** [comment]
I see. Thanks

**Comment by painter1** [comment]
I was wrong, I hadn't looked at the uvcdat.py code well enough.   The fix has to be made in the print statements, and I've done it.  You'll see a VisTrails pull request soon.  Taylor diagrams still don't work, but that's a different issue.
