### ISSUE TITLE
Plot labels: "None" is being printed above plots, should be data set name (?)

### ISSUE THREAD

**Issue by susburrows** [UV-CDAT/uvcmetrics#125]
In the upper left, above the plots, the word "None" is being printed; above difference plots, it says "None,None".  I'm seeing this behavior in a few different versions of the uvcmetrics code.  I think it intended that this field would display the model or observational data set name.

**Comment by painter1** [comment]
The problem was with a new (in March) feature for the user to supply a name for the data set.  If not supplied, it is None.  And this propagates through the system.  I changed a line of code so that it wouldn't propagate; if no name is supplied, you get the same names as before.

**Comment by susburrows** [comment]
Hi Jeff, thanks for working on this.  Is the fix for this available on the devel branch, so I can cross-check that it also works for me?

Also, can you clarify what you mean by "the same names as before"?  I typically call diags.py through the metadiags.py interface, and I assume the dataset names should be the same as the model name that I provide when calling it, and the observational dataset name provided in amwgmaster.py.

Thanks.

**Comment by painter1** [comment]
It is fixed on the devel branch.
"The same names as before" means what was done before there was an option for the user to supply data set names.  These generally are derived from file names.  I tested with diags.py, not metadiags.py.  If you supplied a name to metadiags and it didn't make it all the way through to the output, then we'll have to treat that as a different issue, probably for Brian to work on.

**Comment by susburrows** [comment]
Thanks, @painter1 !  I'll test the fix and let you know if I encounter any issues.
