### ISSUE TITLE
Extensions on maps and colorbar in Diags.py

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/uvcmetrics#191]
It looks like we need to have extension arrows on the color maps for some plots. 
The NCAR AMWG doesn’t have them so it gives us a false sense of the magnitude of the variable.
This may involve adding some logic. We are using prescribed ranges so you will have to check to see if the prescribed data range is larger than the variable range.
I have attached 2 plots: one from DIAGS.py and the other from the AMWG diagnostic package.
DIAGS.py puts white where the data is beyond the prescribed data range. NCAR’s AMWG seems to ignore the value.
![set5_ann_prect_gpcp_global-combined](https://cloud.githubusercontent.com/assets/14208252/15786436/7bf33a7e-2971-11e6-8306-841ad512b2f3.png)
![set5_ann_prect_gpcp_obsc](https://cloud.githubusercontent.com/assets/14208252/15786439/81574d66-2971-11e6-84c2-602e6b912243.png)

**Comment by doutriaux1** [comment]
@glpotter @mcenerney1  to get the extension levels we do not need any new code.
@glpotter got to the wiki page, list the variables that needs extensions (left or right or both)
@mcenerney1 edit default_levels to have -1.e20 as first level for left arrow and 1.e20 as last level for right arrow. And VOILA!

**Comment by glpotter** [comment]
If the extensions are only plotted if they are needed, can't  we add the extensions to all variables? @mcenerney1 @doutriaux1 ?

**Comment by doutriaux1** [comment]
no they are not plotted only if needed, although that is a good idea for another time, for now it's on or off, so if you want we can always add extensions to the `default_levels` that is very easy. @mcenerney1 to do this after we retrieve the levels (or difflevels) simply add
```python
levels.insert(0,-1.e20)
levels.append(1.e20)
```
Voila.

**Comment by mcenerney1** [comment]
is  ratio=“autot” a keyword to plot?

**Comment by glpotter** [comment]
Here is how I use it:

 

x.plot(s, iso, continents = 4, ratio="autot")

 

 

 

Jerry Potter
UC Davis
Department of Earth and Planetary Sciences
One Shields Ave
Davis, CA 95616
(707) 315-8314
jpotter@ucdavis.edu
