### ISSUE TITLE
regional maps in diags.py need aspect ratio

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/uvcmetrics#192]
There are some regional maps in diags.py that need the aspect ration fixed. I have attached the diags.py output and the AMWG (NCAR) output. Also the difference isn't plotted for the tropics. and the map has double labels (not aligned). The Diags.py output is the last map.

![set5_ann_prect_gpcp_trop_obsc](https://cloud.githubusercontent.com/assets/14208252/15786598/53af6afa-2972-11e6-906c-3484fb3072ec.png)
![set5_ann_prect_gpcp_tropics-combined](https://cloud.githubusercontent.com/assets/14208252/15786637/9715837e-2972-11e6-858a-da18e6ef0657.png)

**Comment by doutriaux1** [comment]
@mcenerney1 simply add `ratio="autot"` to the vcs plot calls, and VOILA!

**Comment by glpotter** [comment]
Also, the latitude range in the metadiags output for "TROPICS"  is different from NCAR AMWG output. The latitude range should be from 40 south to 40 north (-40,40)

**Comment by doutriaux1** [comment]
@glpotter according to https://en.wikipedia.org/wiki/Tropics tropics should be between   23°26′13.7″ south and  23°26′13.7″ north :stuck_out_tongue_winking_eye: Easy fix though.

**Comment by glpotter** [comment]
OK, but the AMWG routine calls the tropics -40 to 40. Who knew? - we have to be like them....

**Comment by glpotter** [comment]
![set5_ann_prect_gpcp_trop_obsc](https://cloud.githubusercontent.com/assets/14208252/16082566/bf7ced54-32c6-11e6-8aa8-fe557b91098e.png)

**Comment by doutriaux1** [comment]
@glpotter I was just teasing you.

**Comment by glpotter** [comment]
interesting that Jeff or whoever did this used the literal definition of tropics without looking at the AMWG set

**Comment by doutriaux1** [comment]
@glpotter it's on aims4 now, generated with:
```
/usr/local/uvcdat/2016-03-16_Mesa/bin/diags --model path=/space1/test_data/alpha6_test_run_001-010,climos=yes,type=model --obs "path=/space1/test_data/obs,climos=yes,filter=f_startswith('GPCP')" --logo no --package AMWG --set 5 --seasons ANN --vars PRECT --outputdir ${HOME}/diags_output --prefix set5 --postfix GPCP --regions Global Tropics
```
Not sure why there is only one plot though. Might be read access issue.

Let me know.

![set5_ann_prect_gpcp_tropics-combined](https://cloud.githubusercontent.com/assets/2781425/16083828/520e8bba-32cb-11e6-99f2-be18d14704a0.png)

**Comment by painter1** [comment]
Brian Smith supplied most of the region definitions.  Though I don't specifically know about "tropics", it must have been him.  He made a reasonable choice, but I agree that NCAR's AMWG is the standard to match here.  FWIW, I've also seen "tropics" defined as -30 to 30.  No doubt you could find people using other ranges if you wanted to look.

**Comment by doutriaux1** [comment]
@glpotter it's fixed in https://github.com/UV-CDAT/uvcmetrics/pull/200

**Comment by isubsmith** [comment]
In my defense, I just copied the region definitions from NCAR definitions.
I didn't arbitrarily make them up or anything :)

**Comment by isubsmith** [comment]
They might define "TROPICS" for lwmg differently than amwg perhaps....?

**Comment by doutriaux1** [comment]
don't worry @isubsmith it was an easy fix
