### ISSUE TITLE
Specifying both --levels and --difflevels causes error

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcmetrics#201]
The offending code is [here](https://github.com/UV-CDAT/uvcmetrics/blob/886fb52cc611cb84004df9b5b1f00ea734fc1136/src/python/frontend/options.py#L215-L222); if you specify both `--levels` and `--difflevels`, it condenses both lists into a single list before passing that to this function, which then fails to recognize two different lists as valid input.

**Comment by chaosphere2112** [comment]
(to clarify: the `levels` argument to the function becomes [levels, difflevels])

**Comment by chaosphere2112** [comment]
(on second thought, it's probably an error in argument parsing; not sure why `levels` would have both sets)

**Comment by doutriaux1** [comment]
@chaosphere2112 I ran:
```
doutriaux1@aims4:[uvcmetrics]:[202_default_for_levels]:[5459]> pb ; diags --model path=/space1/test_data/alpha6_test_run,climos=yes,type=model --obs "path=/space1/test_data/obs/,climos=yes,filter=f_startswith('NCEP')" --logo no --package AMWG --set 5 --seasons JJA --vars Z3 --outputdir /export/doutriaux1/diags_output/amwg_latest --prefix set5 --postfix NCEP --regions Global --varopts 500  --levels 20,30,40,50,60 --difflevels -20,-10,0,10
```
and got this uggly but reasonable reslut:
![set5_jja_z3_500_ncep_global-combined](https://cloud.githubusercontent.com/assets/2781425/16125630/5dca13be-33a9-11e6-8b97-989d2467fa30.png)


can you please provide us with a failing command line?

Thanks.

**Comment by doutriaux1** [comment]
it is actually an issue with `argparse` it appears if the first level is a negative value then `argparse` thinks it is dealing with the next option. using `=` and `quotes ""` solves this 
example:
```
diags --model path=/space1/test_data/alpha6_test_run,climos=yes,type=model --obs "path=/space1/test_data/obs/,climos=yes,filter=f_startswith('ERBE')" --package AMWG --set 5 --seasons ANN --vars CLD --outputdir /export/doutriaux1/diags_output/amwg_latest  --levels -10,0,10,20,30,40,50,60,70,80 --difflevels -30,-15,-10,-6,-4,-2,0,2,4,6,10,15,30
```
fails as described above 
but
```
diags --model path=/space1/test_data/alpha6_test_run,climos=yes,type=model --obs "path=/space1/test_data/obs/,climos=yes,filter=f_startswith('ERBE')" --package AMWG --set 5 --seasons ANN --vars CLD --outputdir /export/doutriaux1/diags_output/amwg_latest  --levels="-10,0,10,20,30,40,50,60,70,80" --difflevels="-30,-15,-10,-6,-4,-2,0,2,4,6,10,15,30"
```
works
