### ISSUE TITLE
Z3 JJA 500 mb  plot error

### ISSUE THREAD

**Issue by glpotter** [UV-CDAT/uvcmetrics#202]
There is something wrong with the z3 500mb NCEP difference plot. See for yourself. Is it the difference values or the choice of the difference intervals? This is a low priority since they shouldn't be comparing the model with this old reanalysis.
![set5_jja_z3_500_ncep_global-combined](https://cloud.githubusercontent.com/assets/14208252/16122219/2c5871da-339b-11e6-803e-28d53642918a.png)

**Comment by glpotter** [comment]
The problem is that we didn't convert the data to hectometers so everything is a factor of 100 larger than the AMWG plots. In any case the difference contours are wrong for the Z3-500 and should be 
dcntrs_Z3_500=(/-1.2,-1,-.8,-.6,-.4,-.2,-.1,0,.1,.2,.4,.6,.8,1,1.2/) (times 100) we have

-135 -125 -115 -95 -85 -75 -65 -55 -45 -25 -15 -5 5 15 25

**Comment by glpotter** [comment]
@doutriaux1 That should be  the Z3500 difference.

**Comment by doutriaux1** [comment]
Thanks that's because we look for Z3 not Z3_500 I'll add this to the code

**Comment by glpotter** [comment]
@doutriaux1 
 Here is the AMWG plot for the same variable. Note difference interval
![set5_jja_z3_500_jra25_obsc](https://cloud.githubusercontent.com/assets/14208252/16123589/6c60bf3a-33a0-11e6-96d1-e85268dfb6b0.png)

**Comment by glpotter** [comment]
@doutriaux1 The same goes for the z3 300mb 

dcntrs_Z3_300=(/-1.8,-1.5,-1.2,-.9,-.6,-.3,-.1,0,.1,.3,.6,.9,1.2,1.5,1.8/) X 100

**Comment by glpotter** [comment]
In fact all those plots that specify levels - the difference plots are wrong.

**Comment by doutriaux1** [comment]
@glpotter fixed in #205

**Comment by doutriaux1** [comment]
![set5_jja_z3_500_ncep_global-combined](https://cloud.githubusercontent.com/assets/2781425/16125322/09e4e716-33a8-11e6-9d05-ced2d30d889d.png)
