### ISSUE TITLE
Source attribute shows up in plots

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcmetrics#243]
Looks like the "source" attribute from variables is showing up in the plots; it interacts badly with the new nickname feature from Jim. Hadn't been a problem up till now because we had crummy obs, but using the file at /space1/test_data/obs_for_diagnostics/WILLMOTT_ANN_CLIMO.nc we get this image (using the below command from diags):

```
diags --model path=/Users/fries2/Documents/alpha6_test_run_001-010,climos=yes,type=model,name=alpha6_test_run_001-010 --obs path=/Users/fries2/Documents,climos=yes,filter="f_startswith('WILLMOTT')" --colormaps diff=bl_to_darkred model=rainbow obs=rainbow --package AMWG --set 5 --seasons ANN --vars TREFHT --outputdir /Users/fries2/Documents
```

![figure-set5_global_ann_trefht_plot-combined](https://cloud.githubusercontent.com/assets/718512/17825504/d70884b2-661d-11e6-8643-a19f538907ca.png)

**Comment by mcenerney1** [comment]
I'll take a look at it

**Comment by mcenerney1** [comment]
This is fixed in latest master.
