### ISSUE TITLE
Some command-line jobs which aren't working today

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcmetrics#25]
diags --path ~/metrics_data/cam35_data/ --path2 /Users/painter1/metrics_data/obs_data_5.6/  --filter2 "f_startswith('NCEP')" --package AMWG --set 7 --seasons ANN --vars T --varopts ' Northern Hemisphere'
  File "/Users/painter1/bin/uvcdat-2014.09.10/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/vcs/VCS_validation_functions.py", line 50, in checkedRaise
    raise ex(err)
ValueError: x values must be at least 0.0

could be a VCS error

diags --path ~/metrics_data/cam35_data/ --path2 /Users/painter1/metrics_data/obs_data_5.6/  --filter2 "f_startswith('NCEP')" --package AMWG --set 10 --seasons ANN --vars TS
runs but the plot looks wrong

**Comment by mcenerney1** [comment]
These have been tested more recently and work.
