### ISSUE TITLE
Plotset 7 has "default" in file output

### ISSUE THREAD

**Issue by chaosphere2112** [UV-CDAT/uvcmetrics#258]
Decided to get a head start on the next batch of metadiags problems, and discovered that Plotset 7 is generating images with filenames like `set7_JJA_TS_default_NCEP-combined.png`. The viewer can't find those files, and is checking for what looks to be the "correct" filename, `set7_JJA_TS_NCEP-combined.png`.  You can find some sample output in `/space1/test_data/sam_output/more_plots` from the command: `metadiags --model path=/space/golaz1/ACME_simulations/20160520.A_WCYCL1850.ne30_oEC.edison.alpha6_01/pp/clim_rgr/0070-0099,climos=yes,type=model,name=alpha6_test_run_0070-0099 --obs path=/space1/test_data/obs_for_diagnostics/,climos=yes --outputdir . --package amwg --set 7`

**Comment by chaosphere2112** [comment]
I was using the conda environment `uvcmetrics-test` on AIMS4

**Comment by painter1** [comment]
I fixed this problem; it's in a branch "issue258" and I'll issue a pull request soon.
I don't know how to run the viewer, so I haven't tested it with the viewer.  However, the file names look good.
In testing this fix, I found another issue which was more difficult to debug.  Derived variables were not being plotted for plot set 7.  I fixed this one also, in the same branch.
