### ISSUE TITLE
frontend import uvcmetrics.json

### ISSUE THREAD

**Issue by doutriaux1** [UV-CDAT/uvcmetrics#62]
file is not where frontend __init__.py looks for it

**Comment by isubsmith** [comment]
Can you point us to where it is and/or explain what this is for?

(git blame shows you added the stuff to frontend/__init__.py :) )

Thanks.


On Fri, Feb 20, 2015 at 3:10 PM, Charles Doutriaux <notifications@github.com

**Comment by painter1** [comment]
It's about getting VCS templates into the system.
