### ISSUE TITLE
Showstopper: Seasonal averaging across multiple years

### ISSUE THREAD

**Issue by susburrows** [UV-CDAT/uvcmetrics#65]
Our preference is that DJF seasonal average should use three consecutive months, i.e. D from previous year and JF from current year.

**Comment by painter1** [comment]
The real issue is what to do when one of those three consecutive months isn't available.  I will try to determine what choices will produce customary results, and ensure that the choice made is written as part of the metadata.

**Comment by susburrows** [comment]
That seems reasonable like a reasonable solution: use three consecutive months if possible, and other wise use JF and D from same year, and write to the metadata which choice was made.

**Comment by painter1** [comment]
I am closing this issue because it pertains to climatology.py, which is falling into disuse.  In climatology2.py, the choice of which data to use is entirely under user control.  Whatever you want it to do, it will do.  It needs a simpler user interface, but that's a different issue.
