### ISSUE TITLE
Allow for uvcmetrics package to produce vector graphics

### ISSUE THREAD

**Issue by susburrows** [UV-CDAT/uvcmetrics#72]
Vector graphics (e.g., .eps) in addition to the raster .pngs. Raster images are not usually adequate for publication quality figures. Since we dont want to have to make figures twice, it is quite important that the scripts be capable of producing vector (SVG, PDF, eps, or PS) images.

The graphics format could perhaps be specified through a command-line option.

**Comment by painter1** [comment]
svg output is in diags.py now, alongside png output.  There's no metadata in the svg files, however.
