### ISSUE TITLE
Showstopper: official ACME observational data repository

### ISSUE THREAD

**Issue by susburrows** [UV-CDAT/uvcmetrics#86]
We need an official observational data repository for ACME, and datasets in this repository need to be checked/fixed for CF-compliance and functionality with metrics code.  An initial version of a repository exists on rhea, but it is currently not clear (to the atmosphere team) if someone has responsibility for maintaining it moving forward, if it has found a permanent home, etc..

- Massage all datasets used by ACME to be CF-compliant (including time axis!)
- Available to everyone in ACME in a "comprehensive" version and a "minimal" version ("minimal" fields required to run "top ten" collections) 

A few plots still fail due to non-CF-compliant data sets (usually the time axis is incorrectly specified).  We suggest that rather than adding more special cases to the code, we make our own CF-compliant versions of these files and store them in the "official" obs repository.

(I'm not sure whether this is the best place to track this issue, but it is important and needs a home somewhere)

**Comment by painter1** [comment]
Agreed!  For the ACME project, @isubsmith and I threw all obs sets we knew of into a directory on Lustre.  Instead, we need a collection of data which (1) can be redistributed to the public without restriction, (2) is good enough to be useful to climate scientists, and (3) is a set of NetCDF files conforming to the CF Conventions, and preferably a bit more.   I would also like to see (4) has been updated recently to reflect the latest available observations.

Criteria (2) and (4) require some climate scientists to get involved.  Criterion (3) requires a suitable computer scientist, such as me.

**Comment by painter1** [comment]
Creating the official ACME obs repo is a big task, requires many people, and hasn't even gotten started.  As an interim solution, some of us should create an un-offical non-ACME obs repo.   Also, the documentation may as well include NCAR's instructions for getting their obs sets:
  svn export https://svn-ccsm-release.cgd.ucar.edu/model_diagnostics/atm/cam/obs_data_20140804/

**Comment by susburrows** [comment]
Hi Jeff, I guess the unofficial interim solution is the directory you and Brian set up on rhea.  Thanks for adding the svn instructions here.

**Comment by doutriaux1** [comment]
@painter1 you should talk to @gleckler1 and @durack1 pcmdi is way ahead of acme on this.

**Comment by susburrows** [comment]
Just updating this to note that a discussion on this is ongoing in Confluence:
https://acme-climate.atlassian.net/wiki/display/WORKFLOW/Requirements+for+Observational+Datasets+to+be+used+for+ACME+science

**Comment by susburrows** [comment]
I have migrated copies of all the datasets we had in obs_data into the ACME inputdata repository, which I believe could become a permanent home:
https://acme-svn2.ornl.gov/acme-repo/acme/obs_for_diagnostics/

**Comment by susburrows** [comment]
I think the next step is for us to identify an individual who will take responsibility for being a gatekeeper for new datasets to be submitted to the repository.

**Comment by painter1** [comment]
This supplies all the obs sets which are built in to the present diagnostics, so I am closing this issue.

In the future we will have to find a way to supply obs sets to non-ACME users, and a way to automatically download the data.  But those are different projects.
