### ISSUE TITLE
polar plots fail if hemisphere not specified

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcmetrics#93]
atmosphere plot set 7, the polar plots, requires the user to specify a hemisphere.  The user may well not know to do it, or forget.  There should be a default, used whenever the hemisphere (the aux parameter) is not specified.

You get an exception when the hemisphere/pole is not specified.  I'm labeling this "critical" because I think we should have it fixed for UV-CDAT release 2.2.

**Comment by painter1** [comment]
I just did another bug fix which makes this less of a problem with the GUI.  I'll push it later, but this issue is still a problem sometimes with the GUI, and just as often with the command line.

**Comment by painter1** [comment]
Plot set 12 needs this too.  Just make 'default' or None (or both) an available aux option, with a suitable meaning.

**Comment by painter1** [comment]
I put a default into plot set 12.   While at it, I changed the name used in the GUI to indicate that it doesn't work with the GUI.  This is because it represents plots with tuples, as with my atmos plot set 7.  I'll introduce a separate issue about that.

**Comment by mcenerney1** [comment]
Plot set 7 now crashes from the command line.  If I run
diags.py --outputdir $HOME/Documents/Climatology/ClimateData/diagout/ --model path=$HOME/uvcmetrics_test_data/cam_output/,climos=yes --obs path=$HOME/uvcmetrics_test_data/obs_atmos/,filter='f_startswith("c_t_NCEP")',climos=yes --package AMWG --sets 7 --seasons ANN --vars T --plots yes --varopts = ' Northern Hemisphere'
I get: TypeError: 'NoneType' object is not iterable
It's having trouble running  amwg_plot_spec_vcs_plot

**Comment by painter1** [comment]
amwg_plot_spec_vcs_plot does hardly anything but call canvas.plot.   But make sure that you have the latest version.   The latest version cleans out an internal keyword argument which will confuse VCS.  This may be what your problem is.

**Comment by mcenerney1** [comment]
Yes I have the right version. I see where it cleans out compoundplot.  The problem persists.
I'll continue debugging and try to isolate it better.

**Comment by mcenerney1** [comment]
I'm not seeing why it's failing.  I'll bring in Charles on monday!

**Comment by mcenerney1** [comment]
Create a default as Jeff did for plot set 12.

**Comment by mcenerney1** [comment]
This has been resolved.
