### ISSUE TITLE
atmos plot set 12 in GUI

### ISSUE THREAD

**Issue by painter1** [UV-CDAT/uvcmetrics#96]
I can't get a visible plot for plot set 12 in the GUI.  There are no error messages, and it works in the command-line.  And it uses scatter and line plots, which work in other plot sets.  So I have no clue about what's wrong, or even who's the best person to work on it.  Jim, you're on first!

I don't think this can be done for UV-CDAT release 2.2.

**Comment by mcenerney1** [comment]
This is solved, it's in the devel branch.
